spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
#      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
#      value-serializer: org.apache.kafka.common.serialization.
#      properties:
#        This means that if for some reason the publishing of a message fails, go
#        And retry 10 times before marking that record as fail
#        acks: all
#        retries: 10
#        retry.backoff.ms: 1000
#    admin:
#      properties:
#        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092, dev:9093, dev:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
